[advisories]
ignore = [
  "RUSTSEC-2024-0436", #  paste - no longer maintained
]
[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-3.0",
  "ISC",
  "CDLA-Permissive-2.0",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "GPL-3.0-or-later",
  "Zlib",
]
[bans]
multiple-versions = "allow"
