[advisories]
ignore = []
[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-3.0",
  "ISC",
  "CDLA-Permissive-2.0",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "GPL-3.0-or-later",
  "Zlib",
  "OpenSSL",
]
[bans]
multiple-versions = "allow"
